In [1]:
import pandas as pd
data=pd.read_csv("1960-2024_GDP_USD_clean.csv")
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27458.220154,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1498.875240,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1860.727686,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3641.728939,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448

In [6]:
df_long=data.melt(id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
                  var_name="Year",
                  value_name="GDP")
df_long = df_long.sort_values(by=['Country Name', 'Year'])
df_long.head(100)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,GDP
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,NaN
268,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,1961,NaN
534,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,1962,NaN
800,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,1963,NaN
1066,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,1964,NaN
...,...,...,...,...,...,...
7981,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1990,822.402999
8247,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1991,864.174086
8513,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1992,732.910915
8779,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1993,709.323534
9045,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1994,700.772126

In [7]:
df_long.to_csv('GDP_pivot.csv', index=False, encoding='utf-8-sig')