In [6]:
import pandas as pd

In [1]:
df_forest = pd.read_csv("MAIN_1990-2025forest-area-as-share-of-land-area.csv")

NameError: name 'pd' is not defined

In [13]:
display(df_forest)
display(df_gdp)

,Entity,Code,Year,Share of land covered by forest,Share of land covered by forest (Annotations)
0,Afghanistan,AFG,1990,1.854315,NaN
1,Afghanistan,AFG,1991,1.854315,NaN
2,Afghanistan,AFG,1992,1.854315,NaN
3,Afghanistan,AFG,1993,1.854315,NaN
4,Afghanistan,AFG,1994,1.854315,NaN
...,...,...,...,...,...
7965,Zimbabwe,ZWE,2021,36.132893,NaN
7966,Zimbabwe,ZWE,2022,35.995890,NaN
7967,Zimbabwe,ZWE,2023,35.858887,NaN
7968,Zimbabwe,ZWE,2024,35.721880,NaN
7969,Zimbabwe,ZWE,2025,35.584877,NaN

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4009.320221,4384.187964,4415.999230,4310.889638,5270.432369,5290.950065,6221.206188,7023.065985,NaN,NaN
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,811.165970,633.887202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,6618.335083,6914.178032,6533.711210,5580.603831,6828.756246,6534.248678,6034.272090,6267.186814,NaN,NaN
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1187.109434,NaN,NaN
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.560896,279.158927,275.686274,277.147113,281.888369,294.295520,...,3445.449410,2270.895319,2184.329239,2059.674454,2613.605421,2536.400502,2195.224921,2497.203322,NaN,NaN

In [4]:
print("Rows_count:", df_forest.shape[0])
print("Columns_count:", df_forest.shape[1])

Rows_count: 7970
Columns_count: 5

In [5]:
print("Column_names:")
print(df_forest.columns.tolist())

Column_names:
['Entity', 'Code', 'Year', 'Share of land covered by forest', 'Share of land covered by forest (Annotations)']

In [6]:
print("Data_types:")
print(df_forest.dtypes)

Data_types:
Entity                                               str
Code                                                 str
Year                                               int64
Share of land covered by forest                  float64
Share of land covered by forest (Annotations)        str
dtype: object